accounts/urls.py
from django.urls import path
from django.urls.conf import include
from . import views
from .views import UserCreationForm, UserRegisterView
from django.contrib.auth.views import LoginView, LogoutView


app_name='accounts'
urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('profile', views.profile,name="profile"),
    path('delete/<int:id>',views.dell,name='delete'),
    path('edit_profile', views.edit_profile,name="edit_profile"),
    # path('api_accounts/',include('accounts.api.urls', namespace="accounts_api_return")),
    
]

home/urls.py
from django.conf.urls import url
from django.urls import path,include
from . import views
app_name='home'
urlpatterns = [
    path('',views.main,name='home_page'),
    path('delete/<int:id>',views.dell,name='delete'),
    # apis
    # path('api_home/',include('home.api.urls',namespace="home_api")),
    # # 404
    # url(r'^$',views.main,name="Home"),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from splash.views import splash
from django.conf import settings
from django.conf.urls.static import static
from accounts import views
from django.contrib.auth import views as auth_views

urlpatterns = [ 
    path('admin/', admin.site.urls),
    path('',splash),
    path('home/', include('home.urls',namespace="home")),
    path('about-us/', include('about_us.urls',namespace="about-us")),
    path('accounts/', include('accounts.urls',namespace="accounts")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('news/', include('news.urls',namespace="news")), 
    
    
    
    # path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
    #     name='password_change_done'),

    # path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
    #     name='password_change'),

    # path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
    #  name='password_reset_done'),

    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
    #  name='password_reset_complete'),
    
  path('reset_password/', auth_views.PasswordResetView.as_view(template_name = "registration/reset_password.html"), name ='reset_password'),
  path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name = "registration/password_reset_sent.html"), name ='password_reset_done'),
  path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name = "registration/password_reset_form.html"), name ='password_reset_confirm'),
  path('complete_password_reset/', auth_views.PasswordResetCompleteView.as_view(template_name = "registration/password_reset_complete.html"), name ='password_reset_complete'),
  path('password_change', views.change_password, name='change_password'),
]


urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    city = models.ForeignKey('City',related_name='user_city',on_delete=models.CASCADE,blank=True,null=True)
    state = models.CharField(max_length=100)
    zip = models.PositiveIntegerField(default=0)
    phone_number = models.CharField(max_length=14)
    image = models.ImageField(upload_to='profile/') 
    def __str__(self):
        return str(self.user)
    

@receiver(post_save,sender=User)
def create_user_profile(sender,instance,created,**kwargs):
    if created:
        Profile.objects.create(user=instance) 
class City(models.Model):
    name = models.CharField(max_length=30)
    def __str__(self):
        return self.name
# Models for stocks followed by user


class UserFollowedStocks(models.Model):
    user_followed_stocks = models.CharField(max_length=30,unique=True)
    def save(self, *args, **kwargs):
      if UserFollowedStocks.objects.count() > 3:
        return
      super(UserFollowedStocks, self).save(*args, **kwargs)
    def __str__(self):
        return str(self.user_followed_stocks)

accounts/views.py
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponseRedirectBase
from django.shortcuts import render,HttpResponseRedirect,redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from .form import SignUpForm,UserForm,ProfileForm,FollowedStockForm
from django.urls import reverse
from django.shortcuts import redirect
from .models import Profile,UserFollowedStocks
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm 
from django.utils.translation import ugettext as _

class UserRegisterView(generic.CreateView):
        form_class = SignUpForm
        template_name = 'registration/register.html'
        success_url = reverse_lazy('login')

@login_required
def profile(request):
    profile = Profile.objects.get(user = request.user)
    if request.method=='POST':
        form = FollowedStockForm(request.POST or None)
        if form.is_valid():
            form.save() 
        return redirect('accounts:profile')
    else:
        follow_stock = UserFollowedStocks.objects.all()
        return  render(request, 'profile.html', {'profile':profile,
                                                 'follow_stock':follow_stock})


@login_required
def edit_profile(request):
    profile = Profile.objects.get(user = request.user)
    if request.method == "POST":
        userform = UserForm(request.POST,instance=request.user)
        profileform = ProfileForm(request.POST, request.FILES,instance=profile)
        if userform.is_valid() and profileform.is_valid():
            userform.save()
            my_profile = profileform.save(commit = False)
            my_profile.user = request.user
            my_profile.save()
            return redirect(reverse('accounts:profile'))
    else:
        userform = UserForm(instance=request.user)
        profileform = ProfileForm(instance=profile)
    return render(request,'edit-profile.html',{'userform':userform,
                                               'profileform':profileform})


def dell(request,id):
    item = UserFollowedStocks.objects.get(id=id)
    item.delete()
    return redirect('accounts:profile')

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, _('Your password was successfully updated!'))
            return redirect('accounts:change_password')
        else:
            messages.error(request, _('Please correct the error below.'))
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'registration/password_change.html', {'form': form})

accounts/templates/content/edit_pro_continent.html
{% load static %}
<!-- loading bootstrap4 for forms and buttons  -->
{% load bootstrap4 %}
<div class="main row-card-no-pd mx-auto" style="margin-top:20px;height:300%">

    <!-- Edit profile Page form  -->
    <form method="POST" enctype="multipart/form-data"class="form-group" class="activity card">

        <!-- csrf_token for not hacking and gaps  -->
        {% csrf_token %}

        {% bootstrap_form userform %}
        {% bootstrap_form profileform %}

        <!-- Edit profile Page form button  -->

        {% buttons %}
        <button class="btn btn-secondary" type="submit">Save</button>
        {% endbuttons %}
    
    </form>
</div>

accounts/templates/content/login_content.html
<!-- loading static for images and javascript file links  -->
{% load static %}

<!-- loading bootstrap4 for forms and buttons  -->
{% load bootstrap4 %}

<div class="limiter" >
    <div class="container-login100" style="background: rgb(22, 22, 49);">
        <div class="wrap-login100" style="padding: 60px 130px 33px 95px;">
            <div class="login100-pic js-tilt" data-tilt>
                <img src="{% static 'img/signinimg.png' %}" alt="IMG">
            </div>

            <form class="login100-form validate-form" method="post">
                <span class="login100-form-title">
                    Member Login
                </span>
                {% csrf_token %}
                <div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
                    <input class="input100" type="text" name="username" placeholder="Email">
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
                        <i class="fa fa-user" aria-hidden="true"></i>
                    </span>
                </div>

                <div class="wrap-input100 validate-input" data-validate = "Password is required">
                    <input class="input100" type="password" name="password" placeholder="Password">
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
                        <i class="fa fa-lock" aria-hidden="true"></i>
                    </span>
                </div>
                
                <div class="container-login100-form-btn">
                    <button class="login100-form-btn" type="submit">
                        Login
                    </button>
                </div>

                <div class="text-center p-t-12">
                    <span class="txt1">
                        Forgot
                    </span>
                    <a class="txt2" href="{% url 'reset_password' %}">
                        Username / Password?
                    </a>
                </div>

                <div class="text-center p-t-136">
                    <a class="txt2" href="{% url 'accounts:register' %}">
                        Create your Account
                        <i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>




<!--===============================================================================================-->	
<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'vendor/tilt/tilt.jquery.min.js' %}"></script>
<script >
    $('.js-tilt').tilt({
        scale: 1.1
    })
</script>
<!--===============================================================================================-->
<script src="{% static 'js/main.js' %}"></script>

accounts/templates/content/pro_continent.html
{% load static %}

<!-- User Information -->
<div class="user-box first-box">
    <div class="activity card"  style="--delay: .2s; height:auto;">
        <div class="profile_header activity-link active">
            <h1>Profile</h1>
        </div>
        <ul class="profile_ul">
            <li><div><span class="tag active activity-link active">Full Name : </span><span class="span_dec">{{profile.user.first_name}} {{profile.user.last_name}}</span></div></li>
            <li><div><span class="tag activity-link active">Email : </span><span class="span_dec">{{profile.user.email}}</span></div></li>
            {% if profile.phone_number %}
            <li><div><span class="tag activity-link active">Phone Num : </span><span class="span_dec">{{profile.phone_number}}</span></div></li>
            {% else %}
            <li><div><span class="tag activity-link active">Phone Num : </span><span>........</span></div></li>
            {% endif %}
            {% if profile.state and profile.city %}
            <li><div><span class="tag activity-link active">Address   : </span><span class="span_dec">{{profile.state|capfirst}} - {{profile.city}}</span></div></li>
            {% else %}
            <li><div><span class="tag activity-link active">Address   : </span><span>........</span></div></li>
            {% endif %}
        </ul>
    </div>
    
    <div class="discount card user_img_container user_pic" style="--delay: .4s">
        {% if profile.image %}
        <div class="user_img">
            <img src="{{profile.image.url}}" alt="This is The User Image .. " style="width: 280px;height: 280px;">
        </div>
        {% else %}
        <div class="user_img">
            <img src="{% static 'img/user.png' %}" alt="This is The User Image .. " style="width: 280px;height: 280px;">
        </div>
        {% endif %}

    </div>

</div>

<!-- User Stocks Portfolio -->
<div class="user-box first-box " style="margin-bottom: 40px;" >
    <div class="activity card section_user"  style="--delay: .6s; max-height: 700px;">
        <div class="profile_header activity-link active" style="margin-bottom: 30px;">
            <h1>Stocks you need</h1>
        </div>
        <div class="tradingview-widget-container">
            <div class="tradingview-widget-container__widget"></div>
            <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-market-overview.js" async>
            {
            "colorTheme": "dark",
            "dateRange": "12M",
            "showChart": false,
            "locale": "en",
            "width": "100%",
            "height": 500,
            "largeChartUrl": "",
            "isTransparent": true,
            "showSymbolLogo": true,
            "tabs": [
            {
                "title": "Indices",
                "symbols": [
                {
                    "s": "FOREXCOM:SPXUSD",
                    "d": "S&P 500"
                },
                {
                    "s": "FOREXCOM:NSXUSD",
                    "d": "Nasdaq 100"
                },
                {
                    "s": "FOREXCOM:DJI",
                    "d": "Dow 30"
                },
                {
                    "s": "INDEX:NKY",
                    "d": "Nikkei 225"
                },
                {
                    "s": "INDEX:DEU30",
                    "d": "DAX Index"
                },
                {
                    "s": "FOREXCOM:UKXGBP",
                    "d": "FTSE 100"
                }
                ],
                "originalTitle": "Indices"
            },
            {
                "title": "Commodities",
                "symbols": [
                {
                    "s": "CME_MINI:ES1!",
                    "d": "S&P 500"
                },
                {
                    "s": "CME:6E1!",
                    "d": "Euro"
                },
                {
                    "s": "COMEX:GC1!",
                    "d": "Gold"
                },
                {
                    "s": "NYMEX:CL1!",
                    "d": "Crude Oil"
                },
                {
                    "s": "NYMEX:NG1!",
                    "d": "Natural Gas"
                },
                {
                    "s": "CBOT:ZC1!",
                    "d": "Corn"
                }
                ],
                "originalTitle": "Commodities"
            },
            {
                "title": "Bonds",
                "symbols": [
                {
                    "s": "CME:GE1!",
                    "d": "Eurodollar"
                },
                {
                    "s": "CBOT:ZB1!",
                    "d": "T-Bond"
                },
                {
                    "s": "CBOT:UB1!",
                    "d": "Ultra T-Bond"
                },
                {
                    "s": "EUREX:FGBL1!",
                    "d": "Euro Bund"
                },
                {
                    "s": "EUREX:FBTP1!",
                    "d": "Euro BTP"
                },
                {
                    "s": "EUREX:FGBM1!",
                    "d": "Euro BOBL"
                }
                ],
                "originalTitle": "Bonds"
            },
            {
                "title": "Forex",
                "symbols": [
                {
                    "s": "FX:EURUSD"
                },
                {
                    "s": "FX:GBPUSD"
                },
                {
                    "s": "FX:USDJPY"
                },
                {
                    "s": "FX:USDCHF"
                },
                {
                    "s": "FX:AUDUSD"
                },
                {
                    "s": "FX:USDCAD"
                }
                ],
                "originalTitle": "Forex"
            }
            ]
        }
            </script>
        </div>
        <div class="block"></div>
    </div>
    <div class="discount card user_img_container" style="--delay: .8s">
        <div class="add_favor_stock" style="margin-bottom: 50px;">
            <div class="profile_header activity-link active" style="float: left;margin-bottom: 50px;" >
                <h1>
                    Add Your favorite Stock
                </h1>
            </div>
            
            <form action="{% url 'accounts:profile' %}" method="POST">
                {% csrf_token %}
                <input type="text" name="user_followed_stocks" id="stock" placeholder="Enter Stock...">
                <button href="#" type="submit">
                    <span class="plus">+</span> Add
                </button>
            </form>
            <br>
            <small>
                " hint : The maximum number of following stocks you can add is 4 stocks"
            </small>
            <div class="container_followed" style="margin-top:30px;">
                {% for item in follow_stock %}
                <div class="item_stock_followed" style="margin: 0 auto">
                    <h3>{{item}}
                        <div class="del_icon">
                            <a href=" {% url 'accounts:delete' item.id %}">
                                <i style="color:currentColor;" class="fas fa-trash-alt"></i>
                              </a>
                        </div>
                    </h3>
                </div>
                {% endfor %}
             </div>
        </div>

        <div class="account-wrapper" style="--delay: .8s; float:left; margin:0 auto; margin-bottom:30px; margin-top:40px;">
            <div class="account-profile" style="margin-bottom: 40px;">
            {% if profile.image %}
            <img src="{{profile.image.url}}" alt="" style="width: 150px;height: 150px;">
            {% else %}
            <img src="{% static 'img/user.png' %}" alt="" style="width: 150px;height: 150px;">
            {% endif %}
            <div class="blob-wrap">
            <div class="blob"></div>
            <div class="blob"></div>
            <div class="blob"></div>
            </div>
            <div class="account-name">{{profile.user.first_name}} {{profile.user.last_name}}</div>
            <div class="account-title">{{profile.user.email}}</div>
            </div>
        </div>
    </div>
</div>

accounts/templates/content/register_content.html
 <!-- loading static for images and javascript file links  -->
 {% load static %}
 <!-- loading bootstrap4 for forms and buttons  -->
 {% load bootstrap4 %}

    <div class="limiter">
        <div class="container-login100" style="background: rgb(22, 22, 49);">
            <div class="wrap-login100" style="padding: 60px 130px 10px 95px;">
                <div class="login100-pic js-tilt" data-tilt style="margin-top: 80px;">
                    <img src="{% static 'img/signupimg.png' %}" alt="IMG">
                </div>
    
                <form class="login100-form validate-form" method="post">
                    <span class="login100-form-title" style="padding-bottom: 33px;">
                        Member Join
                    </span>
                    {% csrf_token %}
                    <div class="wrap-input100 validate-input">
                        <input class="input100" type="text" name="username" placeholder="username">
                        <span class="focus-input100"></span>
                        <span class="symbol-input100">
                            <i class="fa fa-user" aria-hidden="true"></i>
                        </span>
                    </div>
                    <div class="wrap-input100 validate-input">
                        <input class="input100" type="text" name="first_name" placeholder="First name">
                        <span class="focus-input100"></span>
                        <span class="symbol-input100">
                            <i class="fa fa-user" aria-hidden="true"></i>
                        </span>
                    </div>
                    <div class="wrap-input100 validate-input">
                        <input class="input100" type="text" name="last_name" placeholder="Last name">
                        <span class="focus-input100"></span>
                        <span class="symbol-input100">
                            <i class="fa fa-user" aria-hidden="true"></i>
                        </span>
                    </div>

                    <div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
                        <input class="input100" type="text" name="email" placeholder="email">
                        <span class="focus-input100"></span>
                        <span class="symbol-input100">
                            <i class="fa fa-envelope" aria-hidden="true"></i>
                        </span>
                    </div>
                    
                    <div class="wrap-input100 validate-input" data-validate = "Password is required">
                        <input class="input100" type="password" name="password1" placeholder="Password">
                        <span class="focus-input100"></span>
                        <span class="symbol-input100">
                            <i class="fa fa-lock" aria-hidden="true"></i>
                        </span>
                    </div>

                    <div class="wrap-input100 validate-input" data-validate = "Password is required">
                        <input class="input100" type="password" name="password2" placeholder="Password Confirmation">
                        <span class="focus-input100"></span>
                        <span class="symbol-input100">
                            <i class="fa fa-lock" aria-hidden="true"></i>
                        </span>
                    </div>
                    
                    <div class="container-login100-form-btn">
                        <button class="login100-form-btn" type="submit">
                            Sign Up
                        </button>
                    </div>
                    <div class="text-center p-t-136" style="padding-top: 40px;">
                        <a class="txt2" href="{% url 'login' %}">
                            Already have an account !
                            <i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
    
    
    
    
    <!--===============================================================================================-->	
    <script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'vendor/select2/select2.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'vendor/tilt/tilt.jquery.min.js' %}"></script>
    <script >
        $('.js-tilt').tilt({
            scale: 1.1
        })
    </script>
    <!--===============================================================================================-->
    <script src="{% static 'js/main.js' %}"></script>
                   