accounts/urls.py
from django.urls import path
from django.urls.conf import include
from . import views
from .views import UserCreationForm, UserRegisterView
from django.contrib.auth.views import LoginView, LogoutView


app_name='accounts'
urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('profile', views.profile,name="profile"),
    path('delete/<int:id>',views.dell,name='delete'),
    path('edit_profile', views.edit_profile,name="edit_profile"),
    # path('api_accounts/',include('accounts.api.urls', namespace="accounts_api_return")),
    
]

home/urls.py
from django.conf.urls import url
from django.urls import path,include
from . import views
app_name='home'
urlpatterns = [
    path('',views.main,name='home_page'),
    path('delete/<int:id>',views.dell,name='delete'),
    # apis
    # path('api_home/',include('home.api.urls',namespace="home_api")),
    # # 404
    # url(r'^$',views.main,name="Home"),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from splash.views import splash
from django.conf import settings
from django.conf.urls.static import static
from accounts import views
from django.contrib.auth import views as auth_views

urlpatterns = [ 
    path('admin/', admin.site.urls),
    path('',splash),
    path('home/', include('home.urls',namespace="home")),
    path('about-us/', include('about_us.urls',namespace="about-us")),
    path('accounts/', include('accounts.urls',namespace="accounts")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('news/', include('news.urls',namespace="news")), 
    
    
    
    # path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
    #     name='password_change_done'),

    # path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
    #     name='password_change'),

    # path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
    #  name='password_reset_done'),

    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
    #  name='password_reset_complete'),
    
  path('reset_password/', auth_views.PasswordResetView.as_view(template_name = "registration/reset_password.html"), name ='reset_password'),
  path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name = "registration/password_reset_sent.html"), name ='password_reset_done'),
  path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name = "registration/password_reset_form.html"), name ='password_reset_confirm'),
  path('complete_password_reset/', auth_views.PasswordResetCompleteView.as_view(template_name = "registration/password_reset_complete.html"), name ='password_reset_complete'),
  path('password_change', views.change_password, name='change_password'),
]


urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/account_base.html
<!DOCTYPE html>
<html lang="en">
    {% include "account_head.html" %}
	<body>	
		{% block body_content %}
		
		{% endblock body_content %}
	</body>
</html>

templates/account_head.html
{% load static %}
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' />
    {% block title %}{% endblock title %}
    <link rel="icon" href="{% static 'img/financial-profit.png' %}">
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static 'img/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<!--===============================================================================================-->
</head>

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load active_link_tags %}
<html lang="en">
{% include "head.html" %}
<body class="sidebar-is-reduced">
    <div class="wrapper">
        {% include "sidebar.html" %}
        <div class="main-container">
            {% include "headerbar.html" %}
         {% block body %}
         
         {% endblock body %}
        </div>
        <script src="{% static 'js/base.js' %}"></script>
  </body>
  
  
</html>

templates/head.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
      
        {% endblock title %}
    </title>
    <link rel="icon" href="{% static 'img/financial-profit.png' %}">
    <link rel="stylesheet" href="{% static 'css/base_1.css' %}">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css">
    
    <script src="https://kit.fontawesome.com/cba01bb0d0.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script src="https://cdn.zingchart.com/zingchart.min.js"></script> 
    <script src="https://cdn.amcharts.com/lib/4/core.js"></script>
    <script src="https://cdn.amcharts.com/lib/4/charts.js"></script>
    <script src="https://cdn.amcharts.com/lib/4/themes/animated.js"></script>
    <script src="https://www.amcharts.com/lib/3/themes/dark.js"></script>
    
    
        

</head>

templates/headerbar.html
{% load active_link_tags %}

<div class="header">
    <div class="logo">Finance
    <span class=logo-det>AI</span>
    </div>
        <ul style="text-align: center;">
            <li class=""> <a class="header-link {% active_link 'home:home_page' %} " href="{% url 'home:home_page' %}">Home</a>   </li>
            <li><a class="header-link {% active_link 'news:stock_news' %}" href="{% url 'news:stock_news' %}">Stock News</a></li>
            <li><a class="header-link {% active_link 'about-us:about' %}" href="{% url 'about-us:about' %}">About Us</a></li>
        </ul>
        <label for="#" id="icon">
            <i class="fa fa-bars"></i>
        </label>
        
 </div>

templates/scripts.html
{% load static %}

<script src="{% static 'js/core/jquery.3.2.1.min.js' %}"></script>
<script src="{% static 'js/core/popper.min.js' %}"></script>
<script src="{% static 'js/core/bootstrap.min.js' %}"></script>

<!-- jQuery UI -->
<script src="{% static 'js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js' %}"></script>
<script src="{% static 'js/plugin/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js' %}"></script>

<!-- jQuery Scrollbar -->
<script src="{% static 'js/plugin/jquery-scrollbar/jquery.scrollbar.min.js' %}"></script>


<!-- Chart JS -->
<script src="{% static 'js/plugin/chart.js/chart.min.js' %}"></script>

<!-- jQuery Sparkline -->
<script src="{% static 'js/plugin/jquery.sparkline/jquery.sparkline.min.js' %}"></script>

<!-- Chart Circle -->
<script src="{% static 'js/plugin/chart-circle/circles.min.js' %}"></script>

<!-- Datatables -->
<script src="{% static 'js/plugin/datatables/datatables.min.js' %}"></script>

<!-- Bootstrap Notify -->
<script src="{% static 'js/plugin/bootstrap-notify/bootstrap-notify.min.js' %}"></script>

<!-- jQuery Vector Maps -->
<script src="{% static 'js/plugin/jqvmap/jquery.vmap.min.js' %}"></script>
<script src="{% static 'js/plugin/jqvmap/maps/jquery.vmap.world.js' %}"></script>

<!-- Sweet Alert -->
<script src="{% static 'js/plugin/sweetalert/sweetalert.min.js' %}"></script>

<!-- Atlantis JS -->
<script src="{% static 'js/finance.min.js' %}"></script>

<!-- Atlantis DEMO methods, don't include it in your project! -->
<script src="{% static 'js/setting-demo.js' %}"></script>
<script src="{% static 'js/demo.js' %}"></script>
<script>
    $('#lineChart').sparkline([102,109,120,99,110,105,115], {
        type: 'line',
        height: '70',
        width: '100%',
        lineWidth: '2',
        lineColor: 'rgba(255, 255, 255, .5)',
        fillColor: 'rgba(255, 255, 255, .15)'
    });

    $('#lineChart2').sparkline([99,125,122,105,110,124,115], {
        type: 'line',
        height: '70',
        width: '100%',
        lineWidth: '2',
        lineColor: 'rgba(255, 255, 255, .5)',
        fillColor: 'rgba(255, 255, 255, .15)'
    });

    $('#lineChart3').sparkline([105,103,123,100,95,105,115], {
        type: 'line',
        height: '70',
        width: '100%',
        lineWidth: '2',
        lineColor: 'rgba(255, 255, 255, .5)',
        fillColor: 'rgba(255, 255, 255, .15)'
    });
</script>

templates/sidebar.html
{% load active_link_tags %}

<div class="left-side">
    <a href="{% url 'accounts:profile' %}" class=" {% active_link 'home:home_page' %}">
        <svg width="30" height="30" viewBox="0 0 22 22" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="none">
        <circle cx="12" cy="8" r="5" />
        <path d="M3,21 h18 C 21,12 3,12 3,21"/>
        </svg>
    </a>
    <a href="{% url 'home:home_page' %}" class="{% active_link 'home:home_page' %}">
        <svg viewBox="0 1 511 512" fill="currentColor">
            <path d="M498.7 222.7L289.8 13.8a46.8 46.8 0 00-66.7 0L14.4 222.6l-.2.2A47.2 47.2 0 0047 303h8.3v153.7a55.2 55.2 0 0055.2 55.2h81.7a15 15 0 0015-15V376.5a25.2 25.2 0 0125.2-25.2h48.2a25.2 25.2 0 0125.1 25.2V497a15 15 0 0015 15h81.8a55.2 55.2 0 0055.1-55.2V303.1h7.7a47.2 47.2 0 0033.4-80.4zm-21.2 45.4a17 17 0 01-12.2 5h-22.7a15 15 0 00-15 15v168.7a25.2 25.2 0 01-25.1 25.2h-66.8V376.5a55.2 55.2 0 00-55.1-55.2h-48.2a55.2 55.2 0 00-55.2 55.2V482h-66.7a25.2 25.2 0 01-25.2-25.2V288.1a15 15 0 00-15-15h-23A17.2 17.2 0 0135.5 244L244.4 35a17 17 0 0124.2 0l208.8 208.8v.1a17.2 17.2 0 010 24.2zm0 0" />
        </svg>
    </a>
    <a href="{% url 'news:stock_news' %}" class="{% active_link 'news:stock_news' %}">
        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-newspaper" viewBox="0 0 16 16">
            <path d="M0 2.5A1.5 1.5 0 0 1 1.5 1h11A1.5 1.5 0 0 1 14 2.5v10.528c0 .3-.05.654-.238.972h.738a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 1 1 0v9a1.5 1.5 0 0 1-1.5 1.5H1.497A1.497 1.497 0 0 1 0 13.5v-11zM12 14c.37 0 .654-.211.853-.441.092-.106.147-.279.147-.531V2.5a.5.5 0 0 0-.5-.5h-11a.5.5 0 0 0-.5.5v11c0 .278.223.5.497.5H12z"/>
            <path d="M2 3h10v2H2V3zm0 3h4v3H2V6zm0 4h4v1H2v-1zm0 2h4v1H2v-1zm5-6h2v1H7V6zm3 0h2v1h-2V6zM7 8h2v1H7V8zm3 0h2v1h-2V8zm-3 2h2v1H7v-1zm3 0h2v1h-2v-1zm-3 2h2v1H7v-1zm3 0h2v1h-2v-1z"/>
        </svg>
    </a>
    <a href="{% url 'change_password' %}">
        <svg fill="currentColor" width="30" height="30" >
            <path d="M18 8h-1V6c0-2.76-2.24-5-5-5S7 3.24 7 6v2H6c-1.1 0-2 .9-2 2v10c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2V10c0-1.1-.9-2-2-2zm-6 9c-1.1 0-2-.9-2-2s.9-2 2-2 2 .9 2 2-.9 2-2 2zm3.1-9H8.9V6c0-1.71 1.39-3.1 3.1-3.1 1.71 0 3.1 1.39 3.1 3.1v2z"/>
        </svg>   
    </a>
    
    <a href="{% url 'accounts:edit_profile' %}" class="{% active_link 'accounts:edit_profile' %}">
        <svg viewBox="0 0 512 512" fill="currentColor">
            <path d="M272 512h-32c-26 0-47.2-21.1-47.2-47.1V454c-11-3.5-21.8-8-32.1-13.3l-7.7 7.7a47.1 47.1 0 01-66.7 0l-22.7-22.7a47.1 47.1 0 010-66.7l7.7-7.7c-5.3-10.3-9.8-21-13.3-32.1H47.1c-26 0-47.1-21.1-47.1-47.1v-32.2c0-26 21.1-47.1 47.1-47.1H58c3.5-11 8-21.8 13.3-32.1l-7.7-7.7a47.1 47.1 0 010-66.7l22.7-22.7a47.1 47.1 0 0166.7 0l7.7 7.7c10.3-5.3 21-9.8 32.1-13.3V47.1c0-26 21.1-47.1 47.1-47.1h32.2c26 0 47.1 21.1 47.1 47.1V58c11 3.5 21.8 8 32.1 13.3l7.7-7.7a47.1 47.1 0 0166.7 0l22.7 22.7a47.1 47.1 0 010 66.7l-7.7 7.7c5.3 10.3 9.8 21 13.3 32.1h10.9c26 0 47.1 21.1 47.1 47.1v32.2c0 26-21.1 47.1-47.1 47.1H454c-3.5 11-8 21.8-13.3 32.1l7.7 7.7a47.1 47.1 0 010 66.7l-22.7 22.7a47.1 47.1 0 01-66.7 0l-7.7-7.7c-10.3 5.3-21 9.8-32.1 13.3v10.9c0 26-21.1 47.1-47.1 47.1zM165.8 409.2a176.8 176.8 0 0045.8 19 15 15 0 0111.3 14.5V465c0 9.4 7.7 17.1 17.1 17.1h32.2c9.4 0 17.1-7.7 17.1-17.1v-22.2a15 15 0 0111.3-14.5c16-4.2 31.5-10.6 45.8-19a15 15 0 0118.2 2.3l15.7 15.7a17.1 17.1 0 0024.2 0l22.8-22.8a17.1 17.1 0 000-24.2l-15.7-15.7a15 15 0 01-2.3-18.2 176.8 176.8 0 0019-45.8 15 15 0 0114.5-11.3H465c9.4 0 17.1-7.7 17.1-17.1v-32.2c0-9.4-7.7-17.1-17.1-17.1h-22.2a15 15 0 01-14.5-11.2c-4.2-16.1-10.6-31.6-19-45.9a15 15 0 012.3-18.2l15.7-15.7a17.1 17.1 0 000-24.2l-22.8-22.8a17.1 17.1 0 00-24.2 0l-15.7 15.7a15 15 0 01-18.2 2.3 176.8 176.8 0 00-45.8-19 15 15 0 01-11.3-14.5V47c0-9.4-7.7-17.1-17.1-17.1h-32.2c-9.4 0-17.1 7.7-17.1 17.1v22.2a15 15 0 01-11.3 14.5c-16 4.2-31.5 10.6-45.8 19a15 15 0 01-18.2-2.3l-15.7-15.7a17.1 17.1 0 00-24.2 0l-22.8 22.8a17.1 17.1 0 000 24.2l15.7 15.7a15 15 0 012.3 18.2 176.8 176.8 0 00-19 45.8 15 15 0 01-14.5 11.3H47c-9.4 0-17.1 7.7-17.1 17.1v32.2c0 9.4 7.7 17.1 17.1 17.1h22.2a15 15 0 0114.5 11.3c4.2 16 10.6 31.5 19 45.8a15 15 0 01-2.3 18.2l-15.7 15.7a17.1 17.1 0 000 24.2l22.8 22.8a17.1 17.1 0 0024.2 0l15.7-15.7a15 15 0 0118.2-2.3z" />
            <path d="M256 367.4c-61.4 0-111.4-50-111.4-111.4s50-111.4 111.4-111.4 111.4 50 111.4 111.4-50 111.4-111.4 111.4zm0-192.8a81.5 81.5 0 000 162.8 81.5 81.5 0 000-162.8z" />
        </svg>
    </a>
    <a href="{% url 'accounts:logout' %}" class="logout_icon" style="margin-top: 120px;">
        <svg viewBox="0 0 512 512" fill="currentColor">
            <path d="M255.2 468.6H63.8a21.3 21.3 0 01-21.3-21.2V64.6c0-11.7 9.6-21.2 21.3-21.2h191.4a21.2 21.2 0 100-42.5H63.8A63.9 63.9 0 000 64.6v382.8A63.9 63.9 0 0063.8 511H255a21.2 21.2 0 100-42.5z" />
            <path d="M505.7 240.9L376.4 113.3a21.3 21.3 0 10-29.9 30.3l92.4 91.1H191.4a21.2 21.2 0 100 42.6h247.5l-92.4 91.1a21.3 21.3 0 1029.9 30.3l129.3-127.6a21.3 21.3 0 000-30.2z" />
        </svg>
    </a>
</div>

templates/splash_home.html
{% load static %}
<!doctype html>
<html lang="en">
  {% include 'head.html' %}
  <title>
      {% block title %}
        
      {% endblock title %}
  </title>
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&display=swap" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Montserrat+Alternates:ital,wght@0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600&display=swap" rel="stylesheet">
  <body>
   {% block splash_content %}
     
   {% endblock splash_content %}
    <style>
        #myVideo 
        {
            position: fixed;
            right: 0;
            bottom: 0;
            min-width: 100%;
            min-height: 100%;
        }
        .box 
        {
            position: fixed;
            bottom:0;
            text-align:center;
            clip-path: polygon(100% 53%, 100% 100%, 0 100%, 0 53%, 50% 27%);
            background: #202a42;
            color: #f1f1f1;
            width: 100%;
            height:650px;
            padding-top: 50px;
            border: 18px solid #131b2f;
            text-align: center;
            box-shadow: 1px 1px 13px 2px rgba(127,127,146,0.45);
            -webkit-box-shadow: 1px 1px 13px 2px rgba(127,127,146,0.45);
            -moz-box-shadow: 1px 1px 13px 2px rgba(127,127,146,0.45);
            font-family: 'Ubuntu', sans-serif;
        }
        .content
        {
            line-height: 1.5;
            display: inline-block;
            vertical-align: middle;
            margin-top: 176px;
            padding: 0 50px 0 50px;
        } 
        .content h1 span
        {
            border-bottom: 3px solid #ccc;
            padding-bottom: 10px;
        }
        .btns a
        {
            margin:0 20px;
        }
        .carousel-item p
        {
            text-align: justify;
        }  
       
            
          
    </style>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
  </body>
</html>